config/routes.rb
Rails.application.routes.draw do
  resources :pages do
    resources :sections
  end

  get 'about-us' => 'pages#show', defaults: { id: 1 }, as: :about_us
  get 'travel' => 'pages#show', defaults: { id: 2 }, as: :travel
  get 'stay' => 'pages#show', defaults: { id: 3 }, as: :stay
  get 'schedule' => 'pages#show', defaults: { id: 4 }, as: :schedule
  get 'registry' => 'pages#show', defaults: { id: 5 }, as: :registry

  devise_for :admins
  root 'home#index'

  namespace :admins do
    resources :guests
  end

  post 'set_language' => 'settings#set_language'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         # :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/content_editor.rb
class ContentEditor
  def self.move_section(section, params)
    move_position = params[:section][:move_position].to_i
    if move_position == 1
      section.move_higher
    elsif move_position == -1
      section.move_lower
    end
  end
end

app/models/page.rb
class Page < ActiveRecord::Base
  has_many :sections, -> { order(position: :asc) }

  enum category: [
    :aboutus,
    :travel,
    :stay,
    :schedule,
    :registry
  ]

  def slug
    title.gsub(" ","_").downcase
  end
end

app/models/section.rb
class Section < ActiveRecord::Base
  belongs_to :page

  acts_as_list scope: :page

  before_save :set_defaults

  def set_defaults
    if path.present?
      self.tag = "img"
    else
      self.tag = ""
    end
  end
end

app/controllers/admins/guests_controller.rb
class Admins::GuestsController < ApplicationController
  before_action :authenticate_admin!
  layout "pages"
  before_action :set_guest, only: [:show, :edit, :update]

  def index
    @guests = Guest.all.order(:name)
    @french_speakers = Guest.where(language: 'french').size
    @english_speakers = Guest.where(language: 'english').size
    @total_guests = Guest.all_guests
  end

  def show
    # @guest = Guest.find_by_id(params[:id])
  end

  def edit
  end

  def update
    respond_to do |format|
      if @guest.update(guest_params)
        format.html { redirect_to admins_guests_path, notice: 'Guest was successfully updated.' }
        format.json { render :index, status: :ok }
      else
        format.html { render :edit }
        format.json { render json: @guest.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    def set_guest
      @guest = Guest.find(params[:id])
    end

    def guest_params
      params.require(:guest).permit(:name, :email, :addons, :language)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :set_locale

  def index
    @pages = Page.all
  end

  def set_locale
    I18n.locale = SINGLE_LANGUAGE ? "en" : (session[:language] || I18n.default_locale)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_locale
  layout "pages"

  def show
    @pages = Page.all
    @page = @pages.find_by(id: params[:id])
    @sections = @page.sections.where(archived: false)
  end

  def set_locale
    I18n.locale = session[:language] || I18n.default_locale
  end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  before_action :set_section, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!, only: [:edit, :update, :destroy]

  # GET /sections
  # GET /sections.json
  def index
    @sections = Section.all.order(:position)
  end

  # GET /sections/1
  # GET /sections/1.json
  def show
  end

  # GET /sections/new
  def new
    @page = Page.find(params[:page_id])
    @section = @page.sections.new
    @category = params[:category] || ""
    session[:return_to] = request.referer
  end

  # GET /sections/1/edit
  def edit
    session[:return_to] = request.referer
    @page = Page.find(params[:page_id])
    @section = @page.sections.find_by(id: params[:id])
  end

  # POST /sections
  # POST /sections.json
  def create
    @page = Page.find(params[:page_id])
    @section = @page.sections.new(section_params)

    respond_to do |format|
      if @section.save
        format.html { redirect_to @section.page, notice: 'Section was successfully created.' }
        format.json { render :show, status: :created, location: @section }
      else
        format.html { render :new }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sections/1
  # PATCH/PUT /sections/1.json
  def update
    respond_to do |format|
      ContentEditor.move_section(@section, params)
      if @section.update(section_params)
        format.html { redirect_to @section.page, notice: 'Section was successfully updated.' }
        format.json { render :show, status: :ok, location: @section }
      else
        format.html { render :edit }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sections/1
  # DELETE /sections/1.json
  def destroy
    @section.destroy
    respond_to do |format|
      format.html { redirect_to sections_url, notice: 'Section was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_section
      @section = Section.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def section_params
      params.require(:section).permit(:content, :tag, :category, :french_content, :page_id, :archived, :path, :classname)
    end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  def set_language
    session[:language] = params[:language]
    # I18n.locale = session[:language] || I18n.default_locale
    I18n.locale = "en-us"
    redirect_to :back
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/home/index.html.slim
h1.title 
  = link_to root_path do
    | Sylviane
    span.ampersand &
    | Adam
= render "partials/main_navigation", locals: { pages: @pages }
  
= render "partials/footer_navigation"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Adam & Sylviane</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1, user-scalable=no">
</head>
<body
  data-controller="<%= controller.controller_name %>"
  data-action="<%= controller.action_name %>"
  class="<%= SINGLE_LANGUAGE == true ? "single-language" : "" %>"
>
  <%= render "partials/language_navigation" %>
  <div class="wrapper">
    <%= yield %>
    <% if admin_signed_in? %>
      <%= link_to "Admin Log Out", destroy_admin_session_path, method: :delete %>
    <% end %>
  </div>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script>
    $(document).on('ready page:load', function () {
      $.FroalaEditor.DEFAULTS.key = "mauigB-9E4H-8hjkyE-13u==";
      $('.froala-editor').froalaEditor();
    });
  </script>
  <script src="https://use.typekit.net/kvp2ire.js"></script>
  <script>try{Typekit.load({ async: true });}catch(e){}</script>
</body>
</html>

app/views/layouts/pages.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sylviane & Adam</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1, user-scalable=no">
</head>
<body data-controller="<%= controller.controller_name %>" data-action="<%= controller.action_name %>">
  <%= render "partials/language_navigation" %>
  <div class="wrapper">
    <h1 class="title">
      <%= link_to "Sylviane & Adam", root_path %>
    </h1>

    <%= yield %>
    <% if admin_signed_in? %>
      <%= link_to "Admin Log Out", destroy_admin_session_path, method: :delete %>
    <% end %>
  </div>
  <%= render "partials/footer" %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="https://use.typekit.net/kvp2ire.js"></script>
  <script>try{Typekit.load({ async: true });}catch(e){}</script>

</body>
</html>

app/views/pages/show.html.slim
= render "partials/main_navigation", locals: { :pages => @pages }
/ h1.page-title = I18n.t("main_navigation.#{@page.slug}")
= render partial: 'partials/section_iterator', :locals => { :sections => @sections }

= render "partials/footer_navigation"

app/views/partials/_footer.html.slim
div data-component="footer"
  img.ring src="http://cdn.everything.io/grant.wedding/trinity_ring.png"
  p Adam & Sylviane
  

app/views/partials/_footer_navigation.html.slim
footer(data-component="footer_navigation")
  nav
    ul
      - @pages.each do |page|
        li =link_to I18n.t("main_navigation.#{page.slug}"), page_path(page.id)
      li
        =link_to "RSVP", "https://www.eventbrite.com/e/mariage-adam-and-sylviane-tickets-19463473774", class: "button", role: "button"

app/views/partials/_language_navigation.html.slim
div(data-component="language_navigation")
  nav(style="#{ "visibility: hidden" if SINGLE_LANGUAGE == true }")
    ul
      li
        = form_tag '/set_language' do
          = hidden_field_tag :language, "fr"
          = submit_tag "", class: "french mobile"
          = submit_tag "Français", class: "french desktop"
      li
        = form_tag '/set_language' do
          = hidden_field_tag :language, "en"
          = submit_tag "", class: "english mobile"
          = submit_tag "English", class: "english desktop"

app/views/partials/_main_navigation.html.slim
div(data-component="main_navigation")
  nav
    ul
      li
        =link_to "RSVP", "https://www.eventbrite.com/e/mariage-adam-and-sylviane-tickets-19463473774"
      - @pages.each do |page|
        li =link_to_unless_current I18n.t("main_navigation.#{page.slug}"), send("#{page.slug}_path")

app/views/partials/_section_iterator.html.slim
p
  = link_to "Add new section", new_page_section_path(page_id: @page.id) if admin_signed_in?
- sections.each do |section|
  div data-component="section" class=section.classname
    - if section.tag == 'img'
      = image_tag "//cdn.everything.io/grant.wedding/#{section.path}", class: "float-in-content #{section.classname}"
    - else
      - if I18n.locale == :en
        = section.content.html_safe
      - else
        = section.french_content.html_safe
    p
      - if admin_signed_in?
        div(data-component="admin_bar")
          nav
            ul
              li
                =link_to "Edit above", edit_page_section_path(@page.id, section.id), class: "button", role: "button"
              li
                = form_for [@page, section] do |f|
                  = f.hidden_field :move_position, value: 1
                  = f.submit "↑ UP", role: "button"
              li
                = form_for [@page, section] do |f|
                  = f.hidden_field :move_position, value: -1
                  = f.submit "↓ DOWN", role: "button"
              li
                = form_for [@page, section] do |f|
                  = f.hidden_field :archived, value: true
                  = f.submit "Delete", role: "button"

app/views/sections/_form.html.erb
<ul data-component="tabs" id="section-editor" data-ks-tabs>
  <li class="open" data-persist-key="new_section_1">
    <a href="#text">Text</a>
  </li>
  <li data-persist-key="new_section_2">
    <a href="#image">Image</a>
  </li>
  <li data-persist-key="new_section_3">
    <a href="#custom">Custom</a>
  </li>
</ul>

<%= form_for([@page, @section]) do |f| %>
  <% if @section.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@section.errors.count, "error") %> prohibited this section from being saved:</h2>

      <ul>
      <% @section.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="tab_pane_container">
    <article id="text" data-persist-key="new_section_4">
      <p><strong>Highly Recommended</strong>: For long content, write in a text editor on your computer where it will be saved, then paste in here when finished.</p>

      <div class="field z-priority">
        <%= f.label :content %>
        <%= f.text_area :content, class: "froala-editor" %>
      </div>

      <div class="field">
        <%= f.label :french_content %>
        <%= f.text_area :french_content, class: "froala-editor" %>
      </div>
    </article>

    <article id="image" data-persist-key="new_section_5">
      <div class="row">
        <% (1..55).each do |number| %>
          <% id = number.to_s.rjust(2, "0") %>
          <img
            class="square"
            src="http://cdn.everything.io/grant.wedding/<%= id %>.jpg"
            data-id="<%= id.to_s %>"
          />
        <% end %>
      </div>

      <div class="field">
        <%= f.label :path %>
        <%= f.text_area :path %>
      </div>
    </article>

    <article id="custom" data-persist-key="new_section_6">
      <div class="field">
        <%= f.label :tag %>
        <%= f.text_area :tag %>
      </div>

      <div class="field">
        <%= f.label :classname %>
        <%= f.text_area :classname %>
      </div>
    </article>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sections/edit.html.erb
<h1>Editing Section</h1>

<%= render 'form' %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', page_path(@page.id) %>

app/views/sections/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Sections</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Tag</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sections.each do |section| %>
      <tr>
        <td><%= section.content %></td>
        <td><%= section.tag %></td>
        <td><%= section.category %></td>
        <td><%= link_to 'Show', section %></td>
        <td><%= link_to 'Edit', edit_section_path(section) %></td>
        <td><%= link_to 'Destroy', section, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Section', new_section_path %>

app/views/sections/new.html.erb
<h1>New Section in <%= @page.title %></h1>

<%= render 'form' %>

<%= link_to 'Back', page_path(@page.id) %>

app/views/sections/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @section.content %>
</p>

<p>
  <strong>Tag:</strong>
  <%= @section.tag %>
</p>

<p>
  <strong>Category:</strong>
  <%= @section.category %>
</p>

<%= link_to 'Edit', edit_section_path(@section) %> |
<%= link_to 'Back', sections_path %>